//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dune2000.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dune2000.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application configuration file &apos;{0}&apos; is not found!
        ///Please proceed to Settings to setup the launcher..
        /// </summary>
        internal static string MountError_CONFIG_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_CONFIG_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered reading application configuration file.
        ///Please proceed to Settings to setup the launcher..
        /// </summary>
        internal static string MountError_CONFIG_READ_ERROR {
            get {
                return ResourceManager.GetString("MountError_CONFIG_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game executable &apos;{0}&apos; is not found!
        ///Please proceed to Settings to setup the launcher..
        /// </summary>
        internal static string MountError_EXECUTABLE_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_EXECUTABLE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; is not a valid directory..
        /// </summary>
        internal static string MountError_INVALID_DIRECTORY {
            get {
                return ResourceManager.GetString("MountError_INVALID_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission map (.MAP) file &apos;{0}&apos; is not found..
        /// </summary>
        internal static string MountError_MAP_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_MAP_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered reading mission map (.MAP) file..
        /// </summary>
        internal static string MountError_MAP_READ_ERROR {
            get {
                return ResourceManager.GetString("MountError_MAP_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required mission map (.MAP) file is not defined..
        /// </summary>
        internal static string MountError_MAP_UNDEFINED {
            get {
                return ResourceManager.GetString("MountError_MAP_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered writing mission map file to game mission directory..
        /// </summary>
        internal static string MountError_MAP_WRITE_ERROR {
            get {
                return ResourceManager.GetString("MountError_MAP_WRITE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission data (.MIS) file &apos;{0}&apos; is not found..
        /// </summary>
        internal static string MountError_MIS_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_MIS_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered reading mission data (.MIS) file..
        /// </summary>
        internal static string MountError_MIS_READ_ERROR {
            get {
                return ResourceManager.GetString("MountError_MIS_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required mission data (.MIS) file is not defined..
        /// </summary>
        internal static string MountError_MIS_UNDEFINED {
            get {
                return ResourceManager.GetString("MountError_MIS_UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered writing mission data file to game mission directory..
        /// </summary>
        internal static string MountError_MIS_WRITE_ERROR {
            get {
                return ResourceManager.GetString("MountError_MIS_WRITE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered applying mission modifications..
        /// </summary>
        internal static string MountError_MOD_ERROR {
            get {
                return ResourceManager.GetString("MountError_MOD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission mod file &apos;{0}&apos; is not found..
        /// </summary>
        internal static string MountError_MOD_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_MOD_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered reading mission mod file..
        /// </summary>
        internal static string MountError_MOD_READ_ERROR {
            get {
                return ResourceManager.GetString("MountError_MOD_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be loaded..
        /// </summary>
        internal static string MountError_PARTIAL_ERROR {
            get {
                return ResourceManager.GetString("MountError_PARTIAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game resource &apos;{0}&apos; is not found!
        ///Please proceed to Settings to check the lanucher configuration..
        /// </summary>
        internal static string MountError_RESOURCE_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_RESOURCE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered reading game resource file. 
        ///Check that {0} has correct number of entries..
        /// </summary>
        internal static string MountError_RESOURCE_READ_ERROR {
            get {
                return ResourceManager.GetString("MountError_RESOURCE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission rules (.INI) file &apos;{0}&apos; is not found..
        /// </summary>
        internal static string MountError_RULES_NOTFOUND {
            get {
                return ResourceManager.GetString("MountError_RULES_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered reading mission rules (.INI) file..
        /// </summary>
        internal static string MountError_RULES_READ_ERROR {
            get {
                return ResourceManager.GetString("MountError_RULES_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered writing mission rules file to game mission directory..
        /// </summary>
        internal static string MountError_RULES_WRITE_ERROR {
            get {
                return ResourceManager.GetString("MountError_RULES_WRITE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered writing spawner file to game directory..
        /// </summary>
        internal static string MountError_SPAWNER_WRITE_ERROR {
            get {
                return ResourceManager.GetString("MountError_SPAWNER_WRITE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;undefined&gt;.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
    }
}
